apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    user: syncuser
    secureJsonData:
      password: syncpass
    jsonData:
      database: syncdb
      sslmode: disable
