services:
  # === PostgreSQL Database ===
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: syncuser
      POSTGRES_PASSWORD: syncpass
      POSTGRES_DB: syncdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - syncnet

  # === Sync Server ===
  server:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    command: ["python", "-m", "server.server"]
    environment:
      - DB_HOST=postgres
      - DB_USER=syncuser
      - DB_PASS=syncpass
      - DB_NAME=syncdb
    volumes:
      - ../../storage:/app/storage
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8000:8000"
    networks:
      - syncnet

  # === Sync Client 1 ===
  client1:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    command: ["python", "-m", "client.client"]
    environment:
      - SERVER=http://server:8080
    volumes:
      - ../../synced1:/app/synced
    depends_on:
      - server
    networks:
      - syncnet

  # === Sync Client 2 ===
  client2:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    command: ["python", "-m", "client.client"]
    environment:
      - SERVER=http://server:8080
    volumes:
      - ../../synced2:/app/synced
    depends_on:
      - server
    networks:
      - syncnet

  # === Grafana ===
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3030:3000"
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - syncnet

  # === Prometheus ===
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - server
    networks:
      - syncnet

  # === Postgres Exporter ===
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://syncuser:syncpass@postgres:5432/syncdb?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - syncnet

  tests:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    command: ["pytest", "-v"]
    depends_on:
      - server
    networks:
      - syncnet


volumes:
  pgdata:

networks:
  syncnet:
    driver: bridge
